import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Notifications from './components/Notifications'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import { ReduxProvider } from './redux_toolkit/provider/provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Food App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <ReduxProvider>
              <div className='container mx-auto'>
                  <Notifications/>
                  <Navbar/>
                  {children}
                  <Footer/>
              </div>
        </ReduxProvider>
        </body>
    </html>
  )
}